server:
  port: 8080
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
      mongodb:
        #uri: mongodb://admin:admin@127.0.0.1:27017/ebac?authSource=admin&retryWrites=true&w=majority
        host: ${MONGODB_URL}
        database: produto
        auto-index-creation: true
eureka:
  instance:
    hostname: ${DISCOVERY_HOST:localhost}
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
