version: '3'

services:
  ebac-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    volumes:
      - C:\Users\Micro\IdeaProjects\Java_EBAC\backend-java-ebac\docker\postgresl:/var/lib/postgresql/data2
    networks:
      - postgres-ebac-network
      
  ebac-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "rpires@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - ebac-postgres-compose
    networks:
      - postgres-ebac-network

  ebac-mysql-compose:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: 'vendas_online'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    ports:
      - "3306:3306"

networks: 
  postgres-ebac-network:
    driver: bridge